---
- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - git
      - htop
      - irssi
      - jq
      - links2
      - ranger
      - tig
      - tmux
      - vim
      - zsh
